# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import resource.resource_rc

class Ui_ChessPlayer(object):
    def setupUi(self, ChessPlayer):
        ChessPlayer.setObjectName("ChessPlayer")
        ChessPlayer.resize(394, 427)
        font = QtGui.QFont()
        font.setFamily("黑体")
        ChessPlayer.setFont(font)
        ChessPlayer.setStyleSheet("QMainWindow{background-image: url(:/background1.jpg);}")
        self.centralWidget = QtWidgets.QWidget(ChessPlayer)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.grid = QtWidgets.QGridLayout()
        self.grid.setObjectName("grid")
        self.horizontalLayout_6.addLayout(self.grid)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lv = QtWidgets.QListView(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.lv.setFont(font)
        self.lv.setObjectName("lv")
        self.verticalLayout.addWidget(self.lv)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox{background-image: url(:/newPrefix/button.jpg)}")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_row = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.lineEdit_row.setFont(font)
        self.lineEdit_row.setObjectName("lineEdit_row")
        self.horizontalLayout_4.addWidget(self.lineEdit_row)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_col = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.lineEdit_col.setFont(font)
        self.lineEdit_col.setObjectName("lineEdit_col")
        self.horizontalLayout_4.addWidget(self.lineEdit_col)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lineEdit_num = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.lineEdit_num.setFont(font)
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.horizontalLayout_3.addWidget(self.lineEdit_num)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_y = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.lineEdit_y.setFont(font)
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.horizontalLayout_3.addWidget(self.lineEdit_y)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_sure = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.btn_sure.setFont(font)
        self.btn_sure.setStyleSheet("QPushButton{background-image: url(:/newPrefix/button.jpg)}")
        self.btn_sure.setObjectName("btn_sure")
        self.horizontalLayout_2.addWidget(self.btn_sure)
        self.btn_calc = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.btn_calc.setFont(font)
        self.btn_calc.setStyleSheet("QPushButton{background-image: url(:/newPrefix/button.jpg)}")
        self.btn_calc.setAutoRepeatDelay(300)
        self.btn_calc.setObjectName("btn_calc")
        self.horizontalLayout_2.addWidget(self.btn_calc)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_ans = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.lineEdit_ans.setFont(font)
        self.lineEdit_ans.setObjectName("lineEdit_ans")
        self.horizontalLayout.addWidget(self.lineEdit_ans)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_exit = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton{background-image: url(:/newPrefix/button.jpg)}")
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        ChessPlayer.setCentralWidget(self.centralWidget)

        self.retranslateUi(ChessPlayer)
        QtCore.QMetaObject.connectSlotsByName(ChessPlayer)

    def retranslateUi(self, ChessPlayer):
        _translate = QtCore.QCoreApplication.translate
        ChessPlayer.setWindowTitle(_translate("ChessPlayer", "MainWindow"))
        self.label_3.setText(_translate("ChessPlayer", "系统提供"))
        self.label_7.setText(_translate("ChessPlayer", "选择"))
        self.label.setText(_translate("ChessPlayer", "行数："))
        self.label_2.setText(_translate("ChessPlayer", "列："))
        self.label_6.setText(_translate("ChessPlayer", "棋数："))
        self.label_4.setText(_translate("ChessPlayer", "Y： "))
        self.btn_sure.setText(_translate("ChessPlayer", "确认"))
        self.btn_calc.setText(_translate("ChessPlayer", "计算"))
        self.label_5.setText(_translate("ChessPlayer", "out"))
        self.btn_exit.setText(_translate("ChessPlayer", "退出"))
